# wallust configuration - for wallust version 3.0

backend = "kmeans"

color_space = "labmixed"

palette = "dark16"

threshold = 11

[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'

hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/hypr/wallust/wallust-hyprland.conf'

rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/mango/rofi/wallust/colors-rofi.rasi'
# rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'

waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/mango/waybar/wallust/colors-waybar.css'
# waybar.target = '~/.config/waybar/wallust/colors-waybar.css'

kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/kitty/kitty-colors.conf'

swaync.template = 'colors-swaync.css'
swaync.target = '~/.config/swaync/wallust/colors-wallust.css'


#macchina.template = 'colors-macchina.toml'
#macchina.target = '~/.config/macchina/themes/wallust.toml'

#wezterm.template = 'colors-wezterm.toml'
#wezterm.target = '~/.config/wezterm/colors/wallust.toml'

#zathura.template = 'colors-zathura'
#zathura.target = '~/.config/zathura/zathurarc'
