add_newline = false
palette = "catppuccin_macchiato"
format = """
$directory $git_branch $git_status $golang
$character """
# Starship modules
[character]
success_symbol = "[[󰄛](green) ❯](peach)"
error_symbol = "[[󰄛](red) ❯](peach)"
vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[git_branch]
symbol = "󰘬 "
style = "bold green"
format = "[$symbol $branch(:$remote_branch)](bold fg:sky)"

[golang]
symbol = " "
format = "[$symbol$version]($style) "

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style))'
stashed = ""
modified = " ●$count"
untracked = " ? $count "
staged = " ✓$count "
deleted = " ✘$count "
renamed = " »$count "
conflicted = " ×$count "
ahead = "⇡$count "
behind = "⇣$count "
diverged = "⇕$count "

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = " "
read_only = "  "
style = "bold sky"
format = '[$home_symbol]($style) [ $path ]($style)'
#

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

